module: ListKit
module_version: 0.1.0
clean: true
author: zhbhun
author_url: https://github.com/zhbhun
github_url: https://github.com/zhbhun/ListKit
source_directory: ListKit/Classes
source_host: github
source_host_url: https://github.com/zhbhun/ListKit
min_acl: public
output: docs/apis
exclude: Example/*
theme: apple