{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/listkit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/listkit"]}],"topicSections":[{"generated":true,"title":"Classes","identifiers":["doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKCompositionalBoundarySupplementary","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListDataSource","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListView","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListViewDelegate","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListViewFlowDelegate","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListBaseView","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalBlock","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalCell","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalFooter","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalGroup","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalHeader","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalItem","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSection","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSectionBoundarySupplementary","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSectionFooter","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSectionHeader","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSectionSupplementary","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSupplementary","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalWaterfall","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowFooter","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowHeader","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowItem","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSection","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSectionFooter","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSectionHeader","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSectionSupplementary","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSupplementary","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListItem","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListSection","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListSupplementary","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListViewDelegate","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListDataSource","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListView","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListViewDelegate","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListViewFlowDelegate","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabBar","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabDataSource","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabView"],"anchor":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListDataSnapshot","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListDataSource"],"anchor":"Protocols","generated":true},{"anchor":"Structures","generated":true,"title":"Structures","identifiers":["doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListDataSnapshot","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListEdgeInsets","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFloat","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListSize","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListDataSnapshot"]},{"title":"Type Aliases","anchor":"Type-Aliases","identifiers":["doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalDimension","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListItemView","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListRectAlignment","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListResolver","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListReusableView","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListScrollDirection","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListView","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabDataSnapshot","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabLabel"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListApplyMode"],"anchor":"Enumerations","generated":true,"title":"Enumerations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit"},"metadata":{"symbolKind":"module","modules":[{"name":"ListKit"}],"externalID":"ListKit","roleHeading":"Framework","title":"ListKit","role":"collection"},"hierarchy":{"paths":[[]]},"sections":[],"references":{"doc://org.cocoapods.ListKit/documentation/ListKit/LKTabLabel":{"navigatorTitle":[{"text":"LKTabLabel","kind":"identifier"}],"title":"LKTabLabel","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabLabel","type":"topic","url":"\/documentation\/listkit\/lktablabel","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"LKTabLabel","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListBaseView":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListBaseView","title":"LKListBaseView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LKListBaseView","kind":"identifier"}],"url":"\/documentation\/listkit\/lklistbaseview","role":"symbol","navigatorTitle":[{"text":"LKListBaseView","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKTabDataSource":{"type":"topic","title":"LKTabDataSource","role":"symbol","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LKTabDataSource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LKTabDataSource"}],"kind":"symbol","url":"\/documentation\/listkit\/lktabdatasource","abstract":[{"type":"text","text":"A data source class for managing tab items in a list."}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKTabBar":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabBar","title":"LKTabBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LKTabBar","kind":"identifier"}],"url":"\/documentation\/listkit\/lktabbar","role":"symbol","navigatorTitle":[{"text":"LKTabBar","kind":"identifier"}],"type":"topic","abstract":[{"text":"A custom tab bar class that inherits from ","type":"text"},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListDataSource":{"navigatorTitle":[{"text":"LKListDataSource","kind":"identifier"}],"url":"\/documentation\/listkit\/lklistdatasource","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListDataSource"}],"title":"LKListDataSource","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListDataSource"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListRectAlignment":{"navigatorTitle":[{"text":"LKListRectAlignment","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"LKListRectAlignment","url":"\/documentation\/listkit\/lklistrectalignment","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListRectAlignment","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"LKListRectAlignment","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListResolver":{"title":"LKListResolver","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LKListResolver"}],"type":"topic","kind":"symbol","url":"\/documentation\/listkit\/lklistresolver","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListResolver","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"LKListResolver","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKCompositionalBoundarySupplementary":{"url":"\/documentation\/listkit\/lkcompositionalboundarysupplementary","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKCompositionalBoundarySupplementary","role":"symbol","navigatorTitle":[{"text":"LKCompositionalBoundarySupplementary","kind":"identifier"}],"title":"LKCompositionalBoundarySupplementary","abstract":[{"type":"text","text":"A class representing a compositional boundary supplementary item in a list."},{"type":"text","text":" "},{"type":"text","text":"This class is a subclass of "},{"type":"codeVoice","code":"LKListCompositionalSupplementary"},{"text":" and is used to define","type":"text"},{"type":"text","text":" "},{"type":"text","text":"supplementary views that are positioned at the boundaries of sections in a compositional layout."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LKCompositionalBoundarySupplementary","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListFlowHeader":{"title":"LKListFlowHeader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKListFlowHeader"}],"navigatorTitle":[{"kind":"identifier","text":"LKListFlowHeader"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowHeader","kind":"symbol","type":"topic","url":"\/documentation\/listkit\/lklistflowheader"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListEdgeInsets":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKListEdgeInsets"}],"kind":"symbol","role":"symbol","title":"LKListEdgeInsets","abstract":[{"type":"text","text":"A structure that defines the edge insets for a list in the ListKit framework."}],"navigatorTitle":[{"kind":"identifier","text":"LKListEdgeInsets"}],"url":"\/documentation\/listkit\/lklistedgeinsets","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListEdgeInsets"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListSupplementary":{"role":"symbol","url":"\/documentation\/listkit\/lklistsupplementary","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LKListSupplementary","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"LKListSupplementary","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListSupplementary","title":"LKListSupplementary","abstract":[{"text":"A class representing supplementary views in a list layout.","type":"text"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListFlowSection":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LKListFlowSection","kind":"identifier"}],"navigatorTitle":[{"text":"LKListFlowSection","kind":"identifier"}],"title":"LKListFlowSection","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSection","kind":"symbol","role":"symbol","url":"\/documentation\/listkit\/lklistflowsection"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalSection":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LKListCompositionalSection"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSection","url":"\/documentation\/listkit\/lklistcompositionalsection","abstract":[{"text":"A class representing a compositional section in a list.","type":"text"}],"kind":"symbol","role":"symbol","title":"LKListCompositionalSection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LKListCompositionalSection","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKFlatListDataSnapshot":{"kind":"symbol","navigatorTitle":[{"text":"LKFlatListDataSnapshot","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"A snapshot of the data for a flat list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This struct conforms to "},{"code":"LKListDataSnapshot","type":"codeVoice"},{"type":"text","text":" and is available on iOS 13.0 or later."}],"url":"\/documentation\/listkit\/lkflatlistdatasnapshot","title":"LKFlatListDataSnapshot","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListDataSnapshot","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"LKFlatListDataSnapshot","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListApplyMode":{"role":"symbol","url":"\/documentation\/listkit\/lklistapplymode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LKListApplyMode","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LKListApplyMode"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListApplyMode","title":"LKListApplyMode","abstract":[{"text":"An enumeration that defines the modes for applying changes to a list.","type":"text"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalCell":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LKListCompositionalCell","kind":"identifier"}],"url":"\/documentation\/listkit\/lklistcompositionalcell","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalCell","navigatorTitle":[{"text":"LKListCompositionalCell","kind":"identifier"}],"title":"LKListCompositionalCell","abstract":[{"type":"text","text":"A cell that represents a compositional item in a list."}],"kind":"symbol"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalGroup":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LKListCompositionalGroup"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalGroup","url":"\/documentation\/listkit\/lklistcompositionalgroup","abstract":[{"type":"text","text":"A compositional group that represents a collection of items in a list."}],"kind":"symbol","role":"symbol","title":"LKListCompositionalGroup","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListCompositionalGroup"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListSection":{"role":"symbol","title":"LKListSection","type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListSection","url":"\/documentation\/listkit\/lklistsection","kind":"symbol","navigatorTitle":[{"text":"LKListSection","kind":"identifier"}],"abstract":[{"text":"A generic class representing a section in a list.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LKListSection","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKTabDataSnapshot":{"title":"LKTabDataSnapshot","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKTabDataSnapshot"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabDataSnapshot","url":"\/documentation\/listkit\/lktabdatasnapshot","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"LKTabDataSnapshot","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalSectionBoundarySupplementary":{"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSectionBoundarySupplementary","url":"\/documentation\/listkit\/lklistcompositionalsectionboundarysupplementary","abstract":[{"type":"text","text":"A class representing the boundary supplementary view for a compositional section in a list."}],"navigatorTitle":[{"text":"LKListCompositionalSectionBoundarySupplementary","kind":"identifier"}],"type":"topic","title":"LKListCompositionalSectionBoundarySupplementary","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LKListCompositionalSectionBoundarySupplementary","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKSectionListView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKSectionListView"}],"abstract":[{"text":"A view that displays a list of sections and items.","type":"text"}],"title":"LKSectionListView","navigatorTitle":[{"text":"LKSectionListView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListView","url":"\/documentation\/listkit\/lksectionlistview","type":"topic","kind":"symbol"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListReusableView":{"abstract":[],"role":"symbol","url":"\/documentation\/listkit\/lklistreusableview","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"LKListReusableView","kind":"identifier"}],"kind":"symbol","title":"LKListReusableView","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListReusableView","navigatorTitle":[{"text":"LKListReusableView","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKSectionListDataSnapshot":{"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListDataSnapshot","abstract":[{"text":"A structure representing a snapshot of the data for a sectioned list.","type":"text"}],"title":"LKSectionListDataSnapshot","navigatorTitle":[{"text":"LKSectionListDataSnapshot","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/listkit\/lksectionlistdatasnapshot","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKSectionListDataSnapshot"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListFlowSectionHeader":{"kind":"symbol","url":"\/documentation\/listkit\/lklistflowsectionheader","role":"symbol","title":"LKListFlowSectionHeader","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LKListFlowSectionHeader","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSectionHeader","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LKListFlowSectionHeader"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/ListKitVersionNumber":{"role":"symbol","url":"\/documentation\/listkit\/listkitversionnumber","fragments":[{"kind":"identifier","text":"ListKitVersionNumber"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/ListKitVersionNumber","title":"ListKitVersionNumber","abstract":[]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListFloat":{"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFloat","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListFloat"}],"title":"LKListFloat","navigatorTitle":[{"text":"LKListFloat","kind":"identifier"}],"url":"\/documentation\/listkit\/lklistfloat","abstract":[{"type":"text","text":"A structure representing a list of floating-point values."}],"kind":"symbol"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalFooter":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LKListCompositionalFooter"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalFooter","url":"\/documentation\/listkit\/lklistcompositionalfooter","abstract":[{"type":"text","text":"A class representing the footer supplementary view in a compositional layout."},{"type":"text","text":" "},{"text":"This class inherits from ","type":"text"},{"type":"codeVoice","code":"LKCompositionalBoundarySupplementary"},{"text":" and is used to define","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the footer section in a list compositional layout."}],"kind":"symbol","role":"symbol","title":"LKListCompositionalFooter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKListCompositionalFooter"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListFlowSectionFooter":{"role":"symbol","url":"\/documentation\/listkit\/lklistflowsectionfooter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LKListFlowSectionFooter","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LKListFlowSectionFooter"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSectionFooter","title":"LKListFlowSectionFooter","abstract":[]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalSupplementary":{"kind":"symbol","navigatorTitle":[{"text":"LKListCompositionalSupplementary","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/listkit\/lklistcompositionalsupplementary","abstract":[{"type":"text","text":"A class representing a compositional supplementary view in a list."},{"text":" ","type":"text"},{"text":"This class is a subclass of ","type":"text"},{"type":"codeVoice","code":"LKListSupplementary"},{"text":" and provides additional","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"functionality specific to compositional layouts in a list."}],"title":"LKListCompositionalSupplementary","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSupplementary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LKListCompositionalSupplementary","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalDimension":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalDimension","title":"LKListCompositionalDimension","url":"\/documentation\/listkit\/lklistcompositionaldimension","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListCompositionalDimension"}],"navigatorTitle":[{"text":"LKListCompositionalDimension","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListItem":{"title":"LKListItem","abstract":[{"text":"A generic class representing an item in a list.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListItem","role":"symbol","url":"\/documentation\/listkit\/lklistitem","navigatorTitle":[{"text":"LKListItem","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LKListItem","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListFlowSectionSupplementary":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LKListFlowSectionSupplementary","kind":"identifier"}],"abstract":[],"url":"\/documentation\/listkit\/lklistflowsectionsupplementary","role":"symbol","type":"topic","title":"LKListFlowSectionSupplementary","navigatorTitle":[{"text":"LKListFlowSectionSupplementary","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSectionSupplementary"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListFlowItem":{"kind":"symbol","url":"\/documentation\/listkit\/lklistflowitem","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowItem","title":"LKListFlowItem","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LKListFlowItem"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LKListFlowItem","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListViewDelegate":{"kind":"symbol","navigatorTitle":[{"text":"LKListViewDelegate","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/listkit\/lklistviewdelegate","title":"LKListViewDelegate","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListViewDelegate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListViewDelegate"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListDataSnapshot":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListDataSnapshot","url":"\/documentation\/listkit\/lklistdatasnapshot","title":"LKListDataSnapshot","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"LKListDataSnapshot","kind":"identifier"}],"navigatorTitle":[{"text":"LKListDataSnapshot","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListSize":{"url":"\/documentation\/listkit\/lklistsize","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListSize"}],"navigatorTitle":[{"text":"LKListSize","kind":"identifier"}],"abstract":[{"text":"A structure representing the size of a list in the ListKit framework.","type":"text"},{"type":"text","text":" "},{"text":"This structure is used to define the dimensions of a list.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListSize","kind":"symbol","type":"topic","title":"LKListSize"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListItemView":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListItemView","abstract":[],"url":"\/documentation\/listkit\/lklistitemview","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LKListItemView","kind":"identifier"}],"title":"LKListItemView","navigatorTitle":[{"text":"LKListItemView","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKFlatListDataSource":{"type":"topic","title":"LKFlatListDataSource","url":"\/documentation\/listkit\/lkflatlistdatasource","role":"symbol","navigatorTitle":[{"text":"LKFlatListDataSource","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LKFlatListDataSource","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A data source class for flat list that conforms to "},{"type":"codeVoice","code":"LKListDataSource"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"This class is available on iOS 13.0 and tvOS 13.0 or later."}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalSectionSupplementary":{"abstract":[{"type":"text","text":"A class representing a supplementary view for a compositional section in a list."}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSectionSupplementary","role":"symbol","title":"LKListCompositionalSectionSupplementary","kind":"symbol","url":"\/documentation\/listkit\/lklistcompositionalsectionsupplementary","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKListCompositionalSectionSupplementary"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LKListCompositionalSectionSupplementary"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKSectionListViewDelegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LKSectionListViewDelegate"}],"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/listkit\/lksectionlistviewdelegate","title":"LKSectionListViewDelegate","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListViewDelegate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKSectionListViewDelegate"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalSectionFooter":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSectionFooter","url":"\/documentation\/listkit\/lklistcompositionalsectionfooter","title":"LKListCompositionalSectionFooter","role":"symbol","abstract":[{"type":"text","text":"A class representing the footer supplementary view for a compositional section in a list."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKListCompositionalSectionFooter"}],"navigatorTitle":[{"kind":"identifier","text":"LKListCompositionalSectionFooter"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalWaterfall":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LKListCompositionalWaterfall"}],"role":"symbol","type":"topic","abstract":[{"text":"A class representing a waterfall layout item in a compositional list.","type":"text"}],"url":"\/documentation\/listkit\/lklistcompositionalwaterfall","title":"LKListCompositionalWaterfall","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalWaterfall","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LKListCompositionalWaterfall","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKSectionListDataSource":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKSectionListDataSource"}],"url":"\/documentation\/listkit\/lksectionlistdatasource","navigatorTitle":[{"text":"LKSectionListDataSource","kind":"identifier"}],"abstract":[{"type":"text","text":"A data source class for managing a list of sections and items."}],"kind":"symbol","type":"topic","title":"LKSectionListDataSource","role":"symbol","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListDataSource"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalHeader":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalHeader","url":"\/documentation\/listkit\/lklistcompositionalheader","title":"LKListCompositionalHeader","role":"symbol","abstract":[{"type":"text","text":"A class representing a compositional header for a list."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListCompositionalHeader"}],"navigatorTitle":[{"kind":"identifier","text":"LKListCompositionalHeader"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListFlowSupplementary":{"kind":"symbol","navigatorTitle":[{"text":"LKListFlowSupplementary","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/listkit\/lklistflowsupplementary","title":"LKListFlowSupplementary","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowSupplementary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListFlowSupplementary"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKFlatListViewDelegate":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListViewDelegate","kind":"symbol","type":"topic","url":"\/documentation\/listkit\/lkflatlistviewdelegate","navigatorTitle":[{"kind":"identifier","text":"LKFlatListViewDelegate"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LKFlatListViewDelegate","kind":"identifier"}],"title":"LKFlatListViewDelegate","role":"symbol"},"doc://org.cocoapods.ListKit/documentation/ListKit":{"url":"\/documentation\/listkit","title":"ListKit","type":"topic","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKFlatListViewFlowDelegate":{"title":"LKFlatListViewFlowDelegate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKFlatListViewFlowDelegate"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListViewFlowDelegate","kind":"symbol","url":"\/documentation\/listkit\/lkflatlistviewflowdelegate","role":"symbol","abstract":[],"navigatorTitle":[{"text":"LKFlatListViewFlowDelegate","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKTabView":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKTabView","url":"\/documentation\/listkit\/lktabview","title":"LKTabView","role":"symbol","abstract":[{"type":"text","text":"A custom scroll view that represents a tab view in the ListKit framework."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LKTabView","kind":"identifier"}],"navigatorTitle":[{"text":"LKTabView","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalBlock":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LKListCompositionalBlock"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A compositional block that represents a section or group of items in a list."}],"url":"\/documentation\/listkit\/lklistcompositionalblock","title":"LKListCompositionalBlock","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalBlock","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListCompositionalBlock"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListScrollDirection":{"navigatorTitle":[{"text":"LKListScrollDirection","kind":"identifier"}],"url":"\/documentation\/listkit\/lklistscrolldirection","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKListScrollDirection"}],"title":"LKListScrollDirection","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListScrollDirection"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalSectionHeader":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalSectionHeader","url":"\/documentation\/listkit\/lklistcompositionalsectionheader","title":"LKListCompositionalSectionHeader","role":"symbol","abstract":[{"text":"A class representing the header for a compositional section in a list.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LKListCompositionalSectionHeader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LKListCompositionalSectionHeader"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKSectionListViewFlowDelegate":{"kind":"symbol","title":"LKSectionListViewFlowDelegate","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKSectionListViewFlowDelegate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LKSectionListViewFlowDelegate"}],"url":"\/documentation\/listkit\/lksectionlistviewflowdelegate","role":"symbol","navigatorTitle":[{"text":"LKSectionListViewFlowDelegate","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKFlatListView":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LKFlatListView"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A view that represents a flat list of items."}],"url":"\/documentation\/listkit\/lkflatlistview","title":"LKFlatListView","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKFlatListView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKFlatListView"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListCompositionalItem":{"kind":"symbol","title":"LKListCompositionalItem","type":"topic","role":"symbol","url":"\/documentation\/listkit\/lklistcompositionalitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LKListCompositionalItem"}],"abstract":[],"navigatorTitle":[{"text":"LKListCompositionalItem","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListCompositionalItem"},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListFlowFooter":{"type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListFlowFooter","url":"\/documentation\/listkit\/lklistflowfooter","title":"LKListFlowFooter","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LKListFlowFooter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LKListFlowFooter"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/LKListView":{"role":"symbol","title":"LKListView","type":"topic","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/LKListView","url":"\/documentation\/listkit\/lklistview","kind":"symbol","navigatorTitle":[{"text":"LKListView","kind":"identifier"}],"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LKListView","kind":"identifier"}]},"doc://org.cocoapods.ListKit/documentation/ListKit/ListKitVersionString":{"kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/listkit\/listkitversionstring","title":"ListKitVersionString","identifier":"doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/ListKitVersionString","fragments":[{"kind":"identifier","text":"ListKitVersionString"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Variables","generated":true,"anchor":"Variables","identifiers":["doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/ListKitVersionNumber","doc:\/\/org.cocoapods.ListKit\/documentation\/ListKit\/ListKitVersionString"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}